In [1]:
import numpy as np
from scipy.spatial.distance import jaccard
from scipy.spatial import distance
from numpy import dot
from numpy.linalg import norm

A = np.array([4,5,0,5,1,0,3,2])
B = np.array([0,3,4,3,1,2,1,0])
C = np.array([2,0,1,3,0,4,5,3])


def to_bool(array):
    result = np.array([])
    for num in array:
        if (num != 0):
            num = 1;
        result = np.append(result,num);
    return result;

A_bool = to_bool(A);
B_bool = to_bool(B);
C_bool = to_bool(C);

D_AB = jaccard(A_bool,B_bool)
D_AC = jaccard(A_bool,B_bool)
D_BC = jaccard(B_bool,C_bool)
print(A_bool)
print(B_bool)
print(C_bool)
print(D_AB)
print(D_AC)
print(D_BC)

print(distance.cosine(A_bool,B_bool))
print(distance.cosine(A_bool,C_bool))
print(distance.cosine(B_bool,C_bool))

[1. 1. 0. 1. 1. 0. 1. 1.]
[0. 1. 1. 1. 1. 1. 1. 0.]
[1. 0. 1. 1. 0. 1. 1. 1.]
0.5
0.5
0.5
0.33333333333333337
0.33333333333333337
0.33333333333333337


In [2]:
def to_cluster(array):
    result = np.array([])
    for num in array:
        if (num >= 3):
            num = 1;
        else:
            num = 0;
        result = np.append(result,num);
    return result;

A_clu = to_cluster(A);
B_clu = to_cluster(B);
C_clu = to_cluster(C);
print(A_clu)
print(B_clu)
print(C_clu)

print(jaccard(A_clu,B_clu))
print(jaccard(A_clu,C_clu))
print(jaccard(B_clu,C_clu))

print(distance.cosine(A_clu,B_clu))
print(distance.cosine(A_clu,C_clu))
print(distance.cosine(B_clu,C_clu))

[1. 1. 0. 1. 0. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 1. 1. 1.]
0.6
0.6666666666666666
0.8333333333333334
0.42264973081037416
0.5
0.7113248654051871


In [3]:
def to_norm(array):
    result = np.array([])
    mean = array[np.nonzero(array)].mean()
    for num in array:
        if (num != 0):
            num = num - mean;
        result = np.append(result,num);
    return result;
A_norm = to_norm(A)
B_norm = to_norm(B)
C_norm = to_norm(C)
print(A_norm)
print(B_norm)
print(C_norm)

print(distance.cosine(A_norm,B_norm))
print(distance.cosine(A_norm,C_norm))
print(distance.cosine(B_norm,C_norm))

[ 0.66666667  1.66666667  0.          1.66666667 -2.33333333  0.
 -0.33333333 -1.33333333]
[ 0.          0.66666667  1.66666667  0.66666667 -1.33333333 -0.33333333
 -1.33333333  0.        ]
[-1.  0. -2.  0.  0.  1.  2.  0.]
0.41569345253185686
1.1154700538379252
1.739573996953447
